# Programming language definition
language: cpp

# OS environment
dist: bionic

# Build matrix (OS, compiler)
matrix:
  include:
    - name: "Linux (GCC compiler)"
      os: linux
      compiler: gcc
      env: OS=linux COMPILER=gcc GCC_VERSION=10
      addons:
        apt:
          sources:
            - 'ubuntu-toolchain-r-test'
          packages:
            - g++-7
            - doxygen
            - lcov
          update: true

    - name: "MacOS"
      os: osx
      osx_image: xcode11.4
      env:
        - MATRIX_EVAL="CXX_COMPILER=clang++"

# Which github branches
branches:
  only:
    - master

before_install:
  # gcc
  - if [ "$OS" != "osx" ] && [ "$COMPILER" = "gcc" ]; then export CC="gcc-${GCC_VERSION}" CXX="g++-${GCC_VERSION}"; fi
  # clang, libc++, libc++abi
  - if [ "$OS" != "osx" ] && [ "$COMPILER" = "clang" ]; then export CC="clang-${CLANG_VERSION}" CXX="clang++-${CLANG_VERSION}"; fi
  # brew, doxygen, lcov
  - if [ "$OS" == "osx" ]; then brew update; fi
  - if [ "$OS" == "osx" ]; then brew install doxygen; fi
  - if [ "$OS" == "osx" ]; then brew install lcov; fi
  # project dir
  - PARENTDIR=$(pwd)

install:
  - pip install conan
  - conan user
  - mkdir $PARENTDIR/build
  - cd $PARENTDIR/build
  - conan install $PARENTDIR
  - cmake $PARENTDIR -DCMAKE_BUILD_TYPE=Coverage
  - make

script:
  - make coverage

after_success:
  - bash <(curl -s https://codecov.io/bash) -f coverage_out.info.cleaned || echo "Codecov did not collect coverage reports"

notifications:
  email:
    on_success: never
