language: cpp

dist: bionic

matrix:
  include:
    - name: "Linux"
      os: linux
      env: 
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
      addons:
        apt:
          sources:
            - 'ubuntu-toolchain-r-test'
          packages:
            - g++-7
            - lcov
          update: true

    - name: "MacOS"
      os: osx
      osx_image: xcode11.2
      env:
        - MATRIX_EVAL="CXX_COMPILER=clang++"
      addons:
        homebrew:
          packages:
          - lcov
          update: true

branches:
  only:
    - master

before_install:
  - eval "${MATRIX_EVAL}"

install:
  - pip install --user conan
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then 
    conan user;
    fi
  - mkdir build
  - cd build
  - conan install ..
  - if [ "$TRAVIS_OS_NAME" = "osx"   ]; then 
    cmake .. -DCMAKE_BUILD_TYPE=Debug;
    fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then 
    cmake .. -DCMAKE_BUILD_TYPE=Coverage -DUSE_GCOV=On; 
    fi
  - make

script:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then make coverage;   fi
  - if [ "$TRAVIS_OS_NAME" = "osx"   ]; then make unit_tests; fi 

after_success:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then  bash <(curl -s https://codecov.io/bash); fi

notifications:
  email:
    on_success: never
