language: cpp
dist: bionic

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
            - doxygen
            - lcov
      env:
        - MATRIX_EVAL="CXX_COMPILER=g++-7; sudo update-alternatives --install /usr/bin/gcov gcov /usr/bin/gcov-7 90"

    - os: osx
        osx_image: xcode10.1
        addons:
          homebrew:
            packages:
            - lcov
            - doxygen
            update: true

        env:
          - MATRIX_EVAL="CXX_COMPILER=clang++"

before_install:
  - eval "${MATRIX_EVAL}"
  - PARENTDIR=$(pwd)

install:
  - pip install conan
  - conan user
  - mkdir $PARENTDIR/build
  - cd $PARENTDIR/build
  - conan install $PARENTDIR
  - cmake $PARENTDIR -DCMAKE_BUILD_TYPE=Coverage
  - make

script:
  - make coverage

after_success:
  - bash <(curl -s https://codecov.io/bash) -f coverage_out.info.cleaned || echo "Codecov did not collect coverage reports"
