<<<<<<< HEAD
language: cpp
=======
language: c
>>>>>>> master

dist: bionic

matrix:
  include:
    - name: "Linux"
      os: linux
      env: 
<<<<<<< HEAD
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
=======
        - MATRIX_EVAL="CC=gcc-7"
>>>>>>> master
      addons:
        apt:
          sources:
            - 'ubuntu-toolchain-r-test'
          packages:
<<<<<<< HEAD
            - g++-7
=======
            - gcc-7
>>>>>>> master
            - lcov
          update: true

    - name: "MacOS"
      os: osx
      compiler: clang
      osx_image: xcode11.2
      env:
        - MATRIX_EVAL=""
      addons:
        homebrew:
          packages:
            - lcov
          update: true

branches:
  only:
    - master

before_install:
  - eval "${MATRIX_EVAL}"
  - PARENTDIR=$(pwd)

install:
  - pip install conan
  - conan user
  - mkdir $PARENTDIR/build
  - cd $PARENTDIR/build
  - conan install $PARENTDIR
  - cmake $PARENTDIR -DCMAKE_BUILD_TYPE=Coverage
  - make

script:
  - make coverage

after_success:
  - bash <(curl -s https://codecov.io/bash) -f coverage_out.info.cleaned

notifications:
  email:
    on_success: never
