language: cpp

dist: bionic

matrix:
  include:
    - name: "Linux"
      os: linux
      env: 
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
      addons:
        apt:
          sources:
            - 'ubuntu-toolchain-r-test'
          packages:
            - g++-7
            - lcov
          update: true

branches:
  only:
    - master

before_install:
  - eval "${MATRIX_EVAL}"
  - PARENTDIR=$(pwd)

install:
  - pip install conan
  - conan user
  - mkdir $PARENTDIR/build
  - cd $PARENTDIR/build
  - conan install $PARENTDIR
  - cmake $PARENTDIR -DCMAKE_BUILD_TYPE=Coverage
  - make

script:
  - make coverage

after_success:
  - bash <(curl -s https://codecov.io/bash) -f coverage_out.info.cleaned

notifications:
  email:
    on_success: never
