language: cpp

dist: bionic

matrix:
  include:
    - name: "Linux"
      os: linux
      env: 
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
      addons:
        apt:
          sources:
            - 'ubuntu-toolchain-r-test'
          packages:
            - g++-7
            - lcov

    - name: "MacOS"
      os: osx
      osx_image: xcode10.2
      env:
        - MATRIX_EVAL="CC=gcc && CXX=g++"
      addons:
        homebrew:
          packages:
          - gcc
          - g++
          - lcov
          - conan

branches:
  only:
    - master

before_install:
  - eval "${MATRIX_EVAL}"

install:
  - mkdir build
  - cd build
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then
    pip install conan;
    conan user;
    conan install ..;
    cmake .. -DCMAKE_BUILD_TYPE=Coverage -DUSE_GCOV=On;
    fi
  - if [ "$TRAVIS_OS_NAME" = "osx"   ]; then
    conan user;
    conan install ..;
    cmake .. -DCMAKE_BUILD_TYPE=Debug;
    fi
  - make

script:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then make coverage;   fi
  - if [ "$TRAVIS_OS_NAME" = "osx"   ]; then make unit_tests; fi 

after_success:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then  bash <(curl -s https://codecov.io/bash); fi

notifications:
  email:
    on_success: never
