name: Documentation

on:
  push:
    tags:
      - "*"
    branches: [ main, master ]

jobs:
  build:
    name: Build and publish documentation
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository and submodules
      uses: actions/checkout@v2
      with:
        submodules: recursive
    - uses: actions/setup-python@v2
    - name: Install
      run: |
        make install_doc
    - name: prepare
      run: |
        mkdir build
        cd build
    - name: Build
      run: |
        cmake . -Bbuild
        cmake --build build --target CppTemplate_docs
    - name: Publish
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build/doxygen/html
