name: Documentation

on:
  push:
    tags:
      - "*"

env:
  CPM_SOURCE_CACHE: ${{ github.workspace }}/cpm_modules

jobs:
  build:
    name: Build and publish documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2

      - name: Install
        run: |
          pip install jinja2 Pygments
          sudo apt-get install doxygen

      - name: Build
        run: |
          cd build
          cmake -DCMAKE_BUILD_TYPE=Debug ..
          cmake --build . --config Debug --target CppTemplate_docs

      - name: Publish
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/doxygen/html
